spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大空闲连接数
        max-idle: 8
        #最大阻塞等待时间，-1表示没有限制
        max-wait: -1ms
        #最小空闲连接
        min-idle: 0